[package]
name = "marker-moment"
version = "0.1.0"
description = "An application for marking notable moments during recording sessions"
authors = ["you"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "marker_moment_lib"
crate-type = ["staticlib", "cdylib", "rlib"]
# path = "lib.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
chrono = { version = "0.4.40", features = ["serde"] }
rdev = "0.5.3"
uuid = { version = "1.15.0", features = ["v4", "serde"] }
dirs = "5.0"
log = "0.4.26"
env_logger = "0.11.6"
thiserror = "2.0.11"
anyhow = "1.0.96"
tauri-plugin-dialog = "2"
tauri-plugin-fs = "2"
tauri-plugin-shell = "2"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-global-shortcut = "2"
tauri-plugin-positioner = "2"
